description: An easily-extensible web server framework in Dart.
homepage: https://github.com/angel-dart/angel
name: blood_money
publish_to: none
dependencies: 
  angel_auth: ^1.1.0-alpha
  angel_configuration: ^1.1.0-alpha
  angel_cors: ^1.0.0
  angel_file_service: ^1.1.0
  angel_framework: ^1.1.0-alpha
  angel_jael: ^1.0.0-alpha
  angel_model: ^1.0.0
  angel_serialize: ^1.0.0-alpha
  angel_static: ^1.3.0-alpha
  angel_validate: ^1.0.0
  angular: ^4.0.0
  angular_forms: 1.0.0
  angular_router: ^1.0.0
dev_dependencies: 
  angel_hot: ^1.1.0-alpha
  angel_serialize_generator: ^1.0.0-alpha
  angel_test: ^1.1.0-alpha
  browser: ^0.10.0
  build_runner: ^0.5.0
  console: ^2.2.4
  dart_to_js_script_rewriter: ^1.0.0
  grinder: ^0.8.0
  test: ^0.12.13
environment: 
  sdk: ">=1.19.0"
web:
  compiler:
    debug: dartdevc
transformers:
  - dart_to_js_script_rewriter
  - angel_configuration
  - angular:
      entry_points:
        - web/main.dart
